### ISSUE TITLE
XML files for each Granule and it's Tree structure

### ISSUE THREAD

**Issue by Aniformer** [usnationalarchives/federalregister-api-core#10]
Hi Team, 

We have gone through the corresponding XML files for a few granules and are yet to see a striking pattern in XML tree structure across all or a group of granules. The XML tree structure seems to vary from granule to granule, hence it becomes harder for a script to extract data between the required XML tags. 

Could you provide us with any clarity around why the XML tree structure is what it is for a certain granule? How is the tag <AMDPAR> used? Why does it usually appear below the <REGTEXT> tag? Can a pattern be established for each <AMDPAR> and <REGTEXT> tag? Is there any reason for the <AMDPAR> and <SECTION> tags to occur where they occur in the XML tree? 

Answer to any such questions, would bring us a lot of clarity. Thanking you.

**Comment by peregrinator** [comment]
Please provide a link to the XML you are referring to in order to help us better understand your question. Additionally this document will be helpful in understanding the FederalRegister XML provided by GPO, https://www.govinfo.gov/bulkdata/FR/resources/FDsys_OFR-XML_User-Guide-v1.pdf

**Comment by Aniformer** [comment]
Here is one example each of the two types of XML links I'm referring to : 
1)https://www.federalregister.gov/documents/full_text/xml/2019/02/14/2018-28281.xml 

In the above link, which belongs to a RULE, contains multiple <REGTEXT> child node under their corresponding parent tag. We wanted clarity around why do some <AMDPAR> tags lie outside the <REGTEXT> tree structure, while some lie within it. Similarly sometimes <SECTNO> and <SUBJECT> tags lie outside the <REGTEXT> tree structure and sometimes within, we are unable to understand as to why this variation exists for these tags. Further noticed <REGTEXT> elements are not identical in tree structure, where as some <REGTEXT> elements contain multiple children. Any clarity around the <REGTEXT> tree structure and why these variations occur would be really helpful. 

2) https://www.federalregister.gov/documents/full_text/xml/2019/02/12/2018-27875.xml

In the above link, which belongs to a PRORULE, we have noticed that PRORULES do not contain any <REGTEXT> elements. Our first question is why is this so? The absence of <REGTEXT> elements makes it harder to extract the TITLE and PART info, and the corresponding section and subject info from the <SECTNO> and <SUBJECT> tags since they are not organized under one <REGTEXT> tree structure like for RULE xml links. Secondly, what is the structure of <ADMPAR> tags for PRORULE, some of them appear under the <PART> tag while some of them appear randomly throughout the XML document, we're looking to understand why this is so as well.

**Comment by peregrinator** [comment]
Your best reference for understanding the structure of the XML is this document: https://www.govinfo.gov/bulkdata/FR/resources/FDsys_OFR-XML_User-Guide-v1.pdf

We are actually also consumers of the bulk XML that is produced by the Government Publishing Office and made available here: https://www.govinfo.gov/bulkdata/FR. We offer the XML for individual documents but it is the same XML as available in the bulk packages. Our JSON API offers a normalized version of the data in the XML (misspelled agency names are corrected/normalized, etc.).

Differing document types will have different structures and get marked up to a different degree. A Proposed Rule (PRORULE) is not marked up to the same extant as a Rule (RULE) document. There are various reasons for this ranging from the amount of resources available to markup the original source documents to various publishing pipeline requirements/needs.

The document linked above is your best resource in understanding how to the XML for these documents is structured - it is the reference that we use as well. In general we recommend using the JSON API as we have done a bulk of the hard work in normalizing the structure.

**Comment by Aniformer** [comment]
Hi team, 

We have looked into the document you have provided to us and it was really helpful in giving us more clarity around the definition of the XML tags and what these tags contain. Further, we're looking to understand why certain (RULE) documents appear in a certain pattern such as given in the example:  https://www.federalregister.gov/documents/full_text/xml/2019/02/14/2018-28281.xml 

The <PART> tag is followed by a <REGTEXT> tag which is followed by another <REGTEXT> tag. Where as later on a <PART> tag is followed by  a <REGTEXT> tag and then a <SECTION> tag. 

![2019-04-18_20-12-45](https://user-images.githubusercontent.com/18691429/56369212-86177e80-6216-11e9-85d2-d7dae8d75a79.png)

![2019-03-08_13-18-36](https://user-images.githubusercontent.com/18691429/56369229-92034080-6216-11e9-9338-aad52cadc176.png)

These are one of the many variations noticed in different XML files for different granules depending on whether they are (PRORULE) or (RULE) documents. 

Any documentation around why these documents consist these varying patterns will help us a ton! 

Thank you, 
Anirudh

**Comment by peregrinator** [comment]
You may be interested in the Document Drafting Handbook which is the guidance given to agencies when creating their documents. That is available here, https://www.archives.gov/federal-register/write/handbook, and describes how documents of various types should be structured. In general I believe the XML markup is creating based on those guidelines.

The XML markup derives from the markup that is used to produce the print editions of the Federal Register and thus may contain elements that make more sense in a print context (determining font size, weight, etc.) than as logical data elements.

Perhaps you can describe how you're hoping to use the XML and we can suggest routes to accomplish that.
