### ISSUE TITLE
JSON Output for Regulatory Entities 

### ISSUE THREAD

**Issue by Aniformer** [usnationalarchives/federalregister-api-core#11]
Hi team, 

https://www.ecfr.gov/cgi-bin/text-idx?SID=bfc91a80d3ef7bf37d3f3d38432993b7&mc=true&tpl=/agencylist.tpl. If you navigate to the given link, it provides us with the list of agencies that fall under federal register. 

Is there any API endpoint or json output that would provide us the same information but in a machine readable format? We would like to map the agency name to it's corresponding legal citation i.e - Title, Part, Chapter and Volume info. One of the API calls provides us with the Title and Chapter info, but we also wish to extract the chapter and volume info for each regulatory entity mentioned in the link above. 

Any help would be appreciated. Thank you.

**Comment by peregrinator** [comment]
We don't currently maintain such a list in the FederalRegister.gov system so unfortunately we aren't able to provide such an endpoint at this time.

I might suggest reaching out to GPO the maintainers of ecfr.gov, https://github.com/usgpo.
