### ISSUE TITLE
Type of Change - Available in JSON Format or API Output?

### ISSUE THREAD

**Issue by Aniformer** [usnationalarchives/federalregister-api-core#12]
Hi team, 

One of the outputs of a certain API call made provides us with the Change Description and Change Notification Hyperlink, along with other field values that appear as key value pairs in the json API output. 

I'd like to know if there are any API endpoints, for the "Type Of Change" - such as whether it is an amendment/repeal. We'd also like to extract the "Type of Change" each regulatory change is and if you could provide us with any information to identify that, it would be really helpful. 

Thank you.

**Comment by peregrinator** [comment]
Can you provide a link to the API endpoint you are referring to?

The `action` field of our document API endpoint may be of interest to you. It is not a normalized field but it does contain some additional information about the document type.

See these urls for examples:
https://www.federalregister.gov/api/v1/documents/2019-04785.json
https://www.federalregister.gov/api/v1/documents/2019-04898.json

**Comment by Aniformer** [comment]
This is an example of the API endpoint I was talking about initially : 
https://www.federalregister.gov/api/v1/documents/2019-02516.json. 

It is similar to the API endpoint that you have provided, thank you for giving me some context around the 'action' field. We shall look into it's results and let you know if it provides us with what we're looking for.
