### ISSUE TITLE
Rate Limits for the FedReg API and Full Text XML

### ISSUE THREAD

**Issue by austince** [usnationalarchives/federalregister-api-core#13]
Hi there, thanks for making this open source! 

Does anyone know of documentation on the rate limits for this API and accessing the full text xml for documents?

Thanks again!

**Comment by peregrinator** [comment]
API requests are currently limited to 5 req/second and xml downloads are 1 req/sec. The rate limits are designed for ongoing usage patterns rather than bulk downloads of the data.

Thanks!

**Comment by austince** [comment]
Great, thank you!
