### ISSUE TITLE
Type of change for updates made at section level

### ISSUE THREAD

**Issue by Aniformer** [usnationalarchives/federalregister-api-core#15]
Hi team, 
https://www.federalregister.gov/api/v1/documents/2018-28281.json

In the above API endpoint the 'action' key gives us whether the entire FR document is a rule or a proposed rule. But as noticed in the particular ecfr link for that FR document : https://www.federalregister.gov/documents/2019/02/14/2018-28281/regulatory-capital-rule-implementation-and-transition-of-the-current-expected-credit-losses?utm_campaign=subscription%20mailing%20list&utm_source=federalregister.gov&utm_medium=em

There are multiple updates made for each legal citation at the section level. Is their any API endpoint that could give us the type of change made for an update made for each legal citation at the section level? 

Thank you,
Anirudh

**Comment by peregrinator** [comment]
Hi Anirudh there is not an API endpoint that would provide the information at that level of detail. All of our API endpoints rely on the data present in the document and the type of data you are looking for is not marked up for us to be able to provide API endpoints for (and I don't believe is present in a lot of cases).
