### ISSUE TITLE
Posting Formal Comments

### ISSUE THREAD

**Issue by cdbessig** [usnationalarchives/federalregister-api-core#5]
We are developing an awareness site around a specific issue that is on federal register.  We'd like to give visitors on the site an embedded experience to submit a formal comment.  I reviewed the api and only reading abilities exist.  Is there any way to either post submitted comments directly to a url, api, or other endpoint for automatic inclusion?

If not, can we perhaps store them in our database, and then use an imacro script to submit then automatically on the federal register site on behalf of our users.  Does the site have any submission limits based on ip / time period?  If we were to get 200 comments in a day, we would be submitting 200 forms from the same computer / ip address.

If this isn't the right place to ask, if you can direct me to the appropriate contact/place that would be great!

**Comment by peregrinator** [comment]
Hi Brian, the write comment API that we use for comment submission is via our partnership with Regulations.gov. The write comment API from them is currently only available to government partners.

We would recommend that you direct your users to the comment form on FederalRegister.gov if you'd like them to comment on a document. We provide a way to open the comment form automatically when directing someone to a document (via a button or link for instance) by adding '#open-comment' to the url for the document. Something similar also works for our short urls - so for example:
https://www.federalregister.gov/articles/2015/08/26/2015-21121/submission-for-omb-review-comment-request#open-comment
https://www.federalregister.gov/a/2015-21121/open-comment

There are a number of reasons we recommend that you direct users to the comment form on FederalRegister.gov. Comment forms are configured by the agency and occasionally the fields are updated to add or remove required fields. When a comment form is submitted we are able to present the user with a confirmation of receipt of the comment via a comment tracking number. Additionally after a comment has been submitted we present options for notification when their comment is made public by the agency as well as notifications when related documents are published in the future (usually a final rule or another proposed rule).

Finally the Regulations.gov terms of service, and thus our terms of service, require that comments be submitted by an individual user and not programmatically on their behalf.

We're always open as to how we can best serve the public making it easier for them to participate in the regulatory process. Thanks for reaching out and please let us know if you have questions or other thoughts on this!

**Comment by cdbessig** [comment]
Hey,

Thanks - That was a very well laid out response.  Understand all of the above.  As for government partners, lets say we are a development agency that does a fair share of political projects, is there a web site outlining requirements, or an application for this partnership process?  Or is it a closed invite only partnership atm?

Thanks!

**Comment by peregrinator** [comment]
Our understanding is that the API is only open to internal government agencies at this point. But I would reach out to Regulations.gov via their help desk to see where they currently are in their evolution of this feature.

Again let us know if we can help in any way as you progress in your planning!

**Comment by cdbessig** [comment]
Hello,

Thank you for your email. Please note, I am OOO on 7/18 - 7/20.  I will process my inbox and actionable items upon my return to the office on Monday July 23rd.

If you require an immediate response, please reach out to the general support email. Otherwise, I will answer your request as soon as possible when I return.  Kevin Blackwell and Vincent Oliver will be covering Project Management duties for ACTIVE in-progress projects.  

General Support / Technical Issues
support@creatingdigital.com
Phone 201-475-1288

Vincent Oliver
voliver@creatingdigital.com
Phone 201-475-1288

Kevin Blackwell
kblackwell@creatingdigital.com
Phone: 201-475-1288

Thank you for your understanding.
