### ISSUE TITLE
Cannot submit public comment

### ISSUE THREAD

**Issue by fgregg** [usnationalarchives/federalregister-api-core#7]
For [this 60-day notice](https://www.federalregister.gov/documents/2017/12/21/2017-27454/agency-information-collection-activities-proposed-ecollection-ecomments-requested-reinstatement-with), clicking on "Submit a public comment on this document" does not provide me a way to submit a public comment on this document? 

Tried in Firefox 58.0 and current Chrome. Ubuntu 16.04. Adblockers turned off.

**Comment by peregrinator** [comment]
Answered in federalregister-web#1
